# -*- coding: utf-8 -*-
"""Fill & Market Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/192pAJn__wjLsOQJMMx4Xr-v3Gp1g-UjD

# Data Load
"""

# Importing Libraries
import pandas as pd

# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Changing the work directory
import os
os.chdir("/content/drive/MyDrive/Colab Notebooks")

# Load the Market Data and Fill CSVs
md_df = pd.read_csv('MD-Combined.csv')

fill_df = pd.read_csv('Fills-Combined.csv')

"""# Combining the two DataFrames"""

# Convert 'ExchangePublishTimestamp' and 'ts' columns to datetime objects
fill_df['ExchangePublishTimestamp']=pd.to_datetime(fill_df['ExchangePublishTimestamp'])
md_df['ts']=pd.to_datetime(md_df['ts'])

# Ensure 'Symbol' column is of the same type in both dataframes
fill_df['Symbol'] = fill_df['Symbol'].astype(str) #Changing them both to strings
md_df['Symbol'] = md_df['Symbol'].astype(str)

# Merging
md_fill_df = pd.merge_asof(fill_df.sort_values('ExchangePublishTimestamp'),
                           md_df.sort_values('ts'), left_on='ExchangePublishTimestamp', right_on='ts',
                           by='Symbol', direction='nearest')

"""# Slippage Analysis"""

# Calculate mid-price
md_fill_df['Mid_Price'] = (md_fill_df['bid_price'] + md_fill_df['ask_price']) / 2

# Calculate Slippage
md_fill_df['Slippage'] = abs(md_fill_df['Mid_Price'] - md_fill_df['Price_x'])/md_fill_df['Mid_Price'] * 100 #In %

# Slippage by Firm and Trader
slippage_by_firm = md_fill_df.groupby('Firm')['Slippage'].mean()
slippage_by_firm=slippage_by_firm.sort_values(ascending=True)
slippage_by_trader = md_fill_df.groupby('Trader_x')['Slippage'].mean()
slippage_by_trader=slippage_by_trader.sort_values(ascending=True)

print("Average Slippage By Firm (%): ")
print(slippage_by_firm)
print("\nAverage Slippage By Trader (%): ")
print(slippage_by_trader)

"""We see from the above calculations that they all have very low slippage which indicates better execution relative to the market. 'EIN' has the best numbers among the firms while 'TIE' is the best among the traders.

# Bid-Ask Spread Impact
"""

# Calculate Spread
md_fill_df['Spread'] = md_fill_df['ask_price'] - md_fill_df['bid_price']

# Spread by symbol
spread_by_symbol = md_fill_df.groupby('Symbol')['Spread'].mean()

# Slippage vs Spread by Order Type
slippage_vs_spread = md_fill_df.groupby(['IsBuy_x','IsAggressor'])[['Slippage','Spread']].mean()

print("Average Spread By Symbol: ")
print(spread_by_symbol)
print("\nSlippage vs Spread By Order Type: ")
print(slippage_vs_spread)

"""We see that 'UNICORNZ0' has the wider spread. Almost double of 'RAINBOWZ0'. This could explain why more trades happen for the latter symbol than the former. As there are more participants for 'RAINBOWZ0', the gap between the bid and ask is tighter.
We see that aggressive orders have a wider spread for sell orders while it's the opposite for buy orders even though the difference in the aggressive and passive approach is not much. Interesting thing is Spread and Slippage have an inversely proportional relationship except in the case of buy-passive orders. We have already deduced previously that the market has more neutral sentiment and there's a demand and supply mismatch. Traders are approaching with caution and while overall uncertainty might be higher, the market is relatively stable during the brief window of order execution.

# Liquidity Analysis
"""

# Liquity by symbol
liquidity_by_symbol = md_fill_df.groupby('Symbol')[['bid_qty','ask_qty']].mean()

print("Average Liquidity By Symbol: ")
print(liquidity_by_symbol)

"""Unfortunately, we couldn't get any value for bid_qty but 'UNICORNZ0' has way lower ask_qty mean, which might explain higher slippage and spread for that symbol. Less liquidity can lead to higher spread due to fewer participants and increased risk for market makers. The lack of participation leads to less competition among market makers, allowing them to offer wider bid-ask spreads to increase their profitability and compensate for higher risk."""